apiVersion: v1
kind: Pod
metadata:
  name: hello-world
  labels:
    app: hello-world
spec:
  containers:
  - name: hello-world
    image: nginx:latest
    ports:
    - containerPort: 80
    env:
    - name: FOO
      value: "bar"
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: hello-world-pvc
