apiVersion: v1
kind: PersistentVolume
metadata:
  name: hello-world-pv
spec:
  capacity:
    storage: 512M
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/hello-world"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hello-world-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512M
  storageClassName: standard
